# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
- include_tasks: add-kafka-user.yml
- include_tasks: install-{{kafka_distro}}-kafka.yml
- include_role:
    name: configure-kafka-nodes
- include_tasks: create-kafka-services.yml
- include_tasks: enable-kafka-services.yml
- include_tasks: start-kafka-services.yml
- name: Pausing before creating requested topics
  command: sleep 10
  when: (kafka_topics_list | default([])) != []
- include_tasks: add-kafka-topics.yml
